import Link from "next/link";
import {ArrowRight,CalendarDays,Clock3,DollarSign,Plus,Stethoscope,UsersRound} from "lucide-react";
import {format} from "date-fns";import {es} from "date-fns/locale";
import {Card} from "@/components/ui/card";
import {createClient} from "@/lib/supabase/server";

export default async function Page(){
  const supabase=await createClient();
  const today=new Date();const start=new Date(today);start.setHours(0,0,0,0);const end=new Date(today);end.setHours(23,59,59,999);
  const [turnos,pacientes,clientes,proximos]=await Promise.all([
    supabase.from("gestion_registros").select("id",{count:"exact",head:true}).eq("tipo","turno").gte("creado_en",start.toISOString()).lte("creado_en",end.toISOString()).eq("activo",true),
    supabase.from("gestion_registros").select("id",{count:"exact",head:true}).eq("tipo","mascota").eq("activo",true),
    supabase.from("gestion_registros").select("id",{count:"exact",head:true}).eq("tipo","cliente").eq("activo",true),
    supabase.from("gestion_registros").select("id,nombre,detalle,creado_en").eq("tipo","turno").eq("activo",true).order("creado_en",{ascending:false}).limit(5)
  ]);
  const stats=[{label:"Turnos de hoy",value:String(turnos.count??0),hint:"Registrados durante la jornada",icon:CalendarDays,color:"text-blue-600 bg-blue-50"},{label:"Pacientes",value:String(pacientes.count??0),hint:"Pacientes activos",icon:Stethoscope,color:"text-violet-600 bg-violet-50"},{label:"Clientes",value:String(clientes.count??0),hint:"Clientes activos",icon:UsersRound,color:"text-emerald-600 bg-emerald-50"},{label:"Caja del día",value:"$ 0",hint:"Movimientos registrados",icon:DollarSign,color:"text-amber-600 bg-amber-50"}];
  return <div><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm capitalize text-slate-500">{format(today,"EEEE, d 'de' MMMM",{locale:es})}</p><h1 className="mt-1 text-2xl font-bold sm:text-3xl">Buen día 👋</h1><p className="mt-1 text-slate-500">Esto es lo que pasa hoy en tu veterinaria.</p></div><Link href="/admin/agenda" className="flex items-center gap-2 rounded-xl bg-[var(--primario)] px-4 py-3 text-sm font-semibold text-white"><Plus size={18}/> Nuevo turno</Link></div><div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(stat=><Card key={stat.label}><div className="flex items-start justify-between"><div><p className="text-sm text-slate-500">{stat.label}</p><p className="mt-2 text-3xl font-bold">{stat.value}</p></div><span className={`rounded-xl p-3 ${stat.color}`}><stat.icon size={20}/></span></div><p className="mt-4 text-xs text-slate-400">{stat.hint}</p></Card>)}</div><div className="mt-5 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><Card><div className="flex items-center justify-between"><div><h2 className="font-bold">Actividad de turnos</h2><p className="text-sm text-slate-500">Últimos registros</p></div><Link href="/admin/agenda" className="text-sm font-semibold text-[var(--primario)]">Ver agenda</Link></div>{!proximos.data?.length?<div className="flex min-h-72 flex-col items-center justify-center text-center"><span className="rounded-2xl bg-slate-100 p-4 text-slate-400"><Clock3/></span><p className="mt-4 font-semibold">Tu agenda está libre</p><p className="mt-1 text-sm text-slate-500">Creá un turno para empezar a organizar el día.</p></div>:<div className="mt-5 divide-y">{proximos.data.map(turno=><div key={turno.id} className="flex items-center gap-3 py-4"><span className="rounded-xl bg-blue-50 p-2 text-blue-600"><CalendarDays size={18}/></span><div><p className="font-semibold">{turno.nombre}</p><p className="text-sm text-slate-500">{String((turno.detalle as Record<string,unknown>).descripcion??"")}</p></div></div>)}</div>}</Card><Card><h2 className="font-bold">Acciones rápidas</h2><p className="text-sm text-slate-500">Lo que más usás, a mano</p><div className="mt-5 grid gap-2">{[["/admin/clientes","Nuevo cliente",UsersRound],["/admin/mascotas","Nuevo paciente",Stethoscope],["/admin/consultas","Iniciar consulta",CalendarDays],["/admin/caja","Registrar venta",DollarSign]].map(([href,label,Icon])=><Link key={label as string} href={href as string} className="flex items-center gap-3 rounded-xl border border-slate-200 p-3 text-sm font-semibold hover:border-blue-200 hover:bg-blue-50"><span className="rounded-lg bg-slate-100 p-2"><Icon size={17}/></span>{label as string}<ArrowRight className="ml-auto text-slate-400" size={16}/></Link>)}</div></Card></div></div>;
}
