export type ModuleDefinition={slug:string;title:string;group:string;singular:string;description:string};

export const MODULES:readonly ModuleDefinition[]=[
  {slug:"dashboard",title:"Inicio",group:"Clínica",singular:"registro",description:"Administrá inicio con búsqueda, estados y exportación."},
  {slug:"clientes",title:"Clientes",group:"Clínica",singular:"registro",description:"Administrá clientes con búsqueda, estados y exportación."},
  {slug:"mascotas",title:"Pacientes",group:"Clínica",singular:"registro",description:"Administrá pacientes con búsqueda, estados y exportación."},
  {slug:"consultas",title:"Consultas",group:"Clínica",singular:"registro",description:"Administrá consultas con búsqueda, estados y exportación."},
  {slug:"clinica/soap",title:"Notas SOAP",group:"Clínica",singular:"registro",description:"Administrá notas soap con búsqueda, estados y exportación."},
  {slug:"clinica/vacunas",title:"Vacunas",group:"Clínica",singular:"registro",description:"Administrá vacunas con búsqueda, estados y exportación."},
  {slug:"prescripciones",title:"Prescripciones",group:"Clínica",singular:"registro",description:"Administrá prescripciones con búsqueda, estados y exportación."},
  {slug:"laboratorio",title:"Laboratorio",group:"Clínica",singular:"registro",description:"Administrá laboratorio con búsqueda, estados y exportación."},
  {slug:"enfermedades",title:"Diagnósticos",group:"Clínica",singular:"registro",description:"Administrá diagnósticos con búsqueda, estados y exportación."},
  {slug:"medicinas",title:"Medicinas",group:"Clínica",singular:"registro",description:"Administrá medicinas con búsqueda, estados y exportación."},
  {slug:"agenda",title:"Agenda",group:"Agenda",singular:"registro",description:"Administrá agenda con búsqueda, estados y exportación."},
  {slug:"agenda-telefonico",title:"Agenda telefónica",group:"Agenda",singular:"registro",description:"Administrá agenda telefónica con búsqueda, estados y exportación."},
  {slug:"recepcion/checkin",title:"Check-in",group:"Agenda",singular:"registro",description:"Administrá check-in con búsqueda, estados y exportación."},
  {slug:"recepcion/sala-espera",title:"Sala de espera",group:"Agenda",singular:"registro",description:"Administrá sala de espera con búsqueda, estados y exportación."},
  {slug:"lista-espera",title:"Lista de espera",group:"Agenda",singular:"registro",description:"Administrá lista de espera con búsqueda, estados y exportación."},
  {slug:"turnos",title:"Turnos",group:"Agenda",singular:"registro",description:"Administrá turnos con búsqueda, estados y exportación."},
  {slug:"pos",title:"Punto de venta",group:"Comercial",singular:"registro",description:"Administrá punto de venta con búsqueda, estados y exportación."},
  {slug:"caja",title:"Caja",group:"Comercial",singular:"registro",description:"Administrá caja con búsqueda, estados y exportación."},
  {slug:"facturacion",title:"Facturación",group:"Comercial",singular:"registro",description:"Administrá facturación con búsqueda, estados y exportación."},
  {slug:"pagos",title:"Pagos",group:"Comercial",singular:"registro",description:"Administrá pagos con búsqueda, estados y exportación."},
  {slug:"contabilidad",title:"Contabilidad",group:"Comercial",singular:"registro",description:"Administrá contabilidad con búsqueda, estados y exportación."},
  {slug:"inventario",title:"Inventario",group:"Comercial",singular:"registro",description:"Administrá inventario con búsqueda, estados y exportación."},
  {slug:"inventario/lotes",title:"Lotes y vencimientos",group:"Comercial",singular:"registro",description:"Administrá lotes y vencimientos con búsqueda, estados y exportación."},
  {slug:"items",title:"Productos y servicios",group:"Comercial",singular:"registro",description:"Administrá productos y servicios con búsqueda, estados y exportación."},
  {slug:"stock",title:"Stock",group:"Comercial",singular:"registro",description:"Administrá stock con búsqueda, estados y exportación."},
  {slug:"proveedores",title:"Proveedores",group:"Comercial",singular:"registro",description:"Administrá proveedores con búsqueda, estados y exportación."},
  {slug:"compras",title:"Compras",group:"Comercial",singular:"registro",description:"Administrá compras con búsqueda, estados y exportación."},
  {slug:"ordenes-compra",title:"Órdenes de compra",group:"Comercial",singular:"registro",description:"Administrá órdenes de compra con búsqueda, estados y exportación."},
  {slug:"remitos",title:"Remitos",group:"Comercial",singular:"registro",description:"Administrá remitos con búsqueda, estados y exportación."},
  {slug:"pedidos",title:"Pedidos",group:"Comercial",singular:"registro",description:"Administrá pedidos con búsqueda, estados y exportación."},
  {slug:"peluqueria",title:"Peluquería",group:"Servicios",singular:"registro",description:"Administrá peluquería con búsqueda, estados y exportación."},
  {slug:"guarderia",title:"Guardería",group:"Servicios",singular:"registro",description:"Administrá guardería con búsqueda, estados y exportación."},
  {slug:"planes-salud",title:"Planes de salud",group:"Servicios",singular:"registro",description:"Administrá planes de salud con búsqueda, estados y exportación."},
  {slug:"fidelizacion",title:"Fidelización",group:"Crecimiento",singular:"registro",description:"Administrá fidelización con búsqueda, estados y exportación."},
  {slug:"promociones",title:"Promociones",group:"Crecimiento",singular:"registro",description:"Administrá promociones con búsqueda, estados y exportación."},
  {slug:"marketing",title:"Marketing",group:"Crecimiento",singular:"registro",description:"Administrá marketing con búsqueda, estados y exportación."},
  {slug:"notificaciones",title:"Notificaciones",group:"Crecimiento",singular:"registro",description:"Administrá notificaciones con búsqueda, estados y exportación."},
  {slug:"notificaciones-avanzadas",title:"Notificaciones avanzadas",group:"Crecimiento",singular:"registro",description:"Administrá notificaciones avanzadas con búsqueda, estados y exportación."},
  {slug:"recordatorios",title:"Recordatorios",group:"Crecimiento",singular:"registro",description:"Administrá recordatorios con búsqueda, estados y exportación."},
  {slug:"reclamos",title:"Reclamos",group:"Crecimiento",singular:"registro",description:"Administrá reclamos con búsqueda, estados y exportación."},
  {slug:"documentos",title:"Documentos",group:"Crecimiento",singular:"registro",description:"Administrá documentos con búsqueda, estados y exportación."},
  {slug:"rrhh",title:"RRHH",group:"Equipo",singular:"registro",description:"Administrá rrhh con búsqueda, estados y exportación."},
  {slug:"staff",title:"Staff",group:"Equipo",singular:"registro",description:"Administrá staff con búsqueda, estados y exportación."},
  {slug:"usuarios",title:"Usuarios",group:"Equipo",singular:"registro",description:"Administrá usuarios con búsqueda, estados y exportación."},
  {slug:"roles",title:"Roles y permisos",group:"Equipo",singular:"registro",description:"Administrá roles y permisos con búsqueda, estados y exportación."},
  {slug:"sucursales",title:"Sucursales",group:"Equipo",singular:"registro",description:"Administrá sucursales con búsqueda, estados y exportación."},
  {slug:"reportes",title:"Reportes",group:"Gestión",singular:"registro",description:"Administrá reportes con búsqueda, estados y exportación."},
  {slug:"analytics",title:"Analytics",group:"Gestión",singular:"registro",description:"Administrá analytics con búsqueda, estados y exportación."},
  {slug:"bi-avanzado",title:"BI avanzado",group:"Gestión",singular:"registro",description:"Administrá bi avanzado con búsqueda, estados y exportación."},
  {slug:"auditoria",title:"Auditoría",group:"Gestión",singular:"registro",description:"Administrá auditoría con búsqueda, estados y exportación."},
  {slug:"workflows",title:"Workflows",group:"Gestión",singular:"registro",description:"Administrá workflows con búsqueda, estados y exportación."},
  {slug:"integraciones",title:"Integraciones",group:"Sistema",singular:"registro",description:"Administrá integraciones con búsqueda, estados y exportación."},
  {slug:"marketplace",title:"Marketplace",group:"Sistema",singular:"registro",description:"Administrá marketplace con búsqueda, estados y exportación."},
  {slug:"configuracion",title:"Configuración",group:"Sistema",singular:"registro",description:"Administrá configuración con búsqueda, estados y exportación."},
  {slug:"configuracion/colores",title:"Colores",group:"Sistema",singular:"registro",description:"Administrá colores con búsqueda, estados y exportación."},
  {slug:"configuracion/modulos",title:"Módulos",group:"Sistema",singular:"registro",description:"Administrá módulos con búsqueda, estados y exportación."},
];

export const MODULE_BY_SLUG=new Map(MODULES.map((module)=>[module.slug,module]));
export const MODULE_GROUPS=[...new Set(MODULES.map((module)=>module.group))];
export function getModule(slug:string){return MODULE_BY_SLUG.get(slug)}
