"use client";
import {useState} from "react";
import {useRouter} from "next/navigation";
import {LoaderCircle} from "lucide-react";
import {GevetLogo} from "@/components/brand/gevet-logo";
import {createClient} from "@/lib/supabase/client";
import {passwordUpdateSchema} from "@/lib/validators/auth";

export function UpdatePasswordForm(){const [loading,setLoading]=useState(false);const [error,setError]=useState<string>();const router=useRouter();async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();if(loading)return;setLoading(true);setError(undefined);const form=new FormData(event.currentTarget);const parsed=passwordUpdateSchema.safeParse({password:form.get("password"),confirmation:form.get("confirmation")});if(!parsed.success){setError(parsed.error.issues[0]?.message);setLoading(false);return}try{const {error:requestError}=await createClient().auth.updateUser({password:parsed.data.password});if(requestError)throw requestError;router.replace("/admin/dashboard");router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"No pudimos actualizar la contraseña")}finally{setLoading(false)}}return <main className="flex min-h-screen items-center justify-center bg-slate-50 px-5"><section className="w-full max-w-md rounded-3xl border border-slate-200 bg-white p-7 shadow-sm sm:p-9"><GevetLogo priority imageClassName="h-12 w-12"/><h1 className="mt-8 text-3xl font-bold">Elegí una contraseña nueva</h1><p className="mt-2 text-slate-500">Usá al menos 8 caracteres y no reutilices una contraseña anterior.</p><form onSubmit={submit} className="mt-7 space-y-4">{[["password","Nueva contraseña"],["confirmation","Repetir contraseña"]].map(([name,label])=><label key={name} className="block text-sm font-medium">{label}<input required minLength={8} maxLength={128} type="password" name={name} autoComplete="new-password" className="mt-1.5 min-h-12 w-full rounded-xl border border-slate-300 px-4 outline-none focus:border-blue-500"/></label>)}{error&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-blue-600 font-semibold text-white disabled:opacity-60">{loading&&<LoaderCircle className="animate-spin" size={18}/>}Guardar contraseña</button></form></section></main>}
